# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---
version: 2
project_name: bridget
before:
  hooks:
    - go mod tidy

release:
  name_template: "Bridget v{{ .Version }}"

changelog:
  use: git
  groups:
    - title: New Features
      regexp: '^feat(\(.+\))?!?:.+$'
      order: 10
    - title: Bug Fixes
      regexp: '^(fix|refactor)(\(.+\))?!?:.+$'
      order: 20
    - title: Documentation updates
      regexp: '^docs(\(.+\))?!?:.+$'
      order: 30
  filters:
    include:
      - '^feat(\(.+\))?!?:.+$'
      - '^(fix|refactor)(\(.+\))?!?:.+$'
      - '^docs(\(.+\))?!?:.+$'

checksum:
  name_template: checksums.txt

builds:
  - main: ./cmd/bridget/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm

kos:
  - main: ./cmd/bridget
    repositories:
      - ghcr.io/nocderechte/bridget
      - docker.io/nocderechte/bridget
    tags:
      - "v{{.Version}}"
      - latest
    labels:
      io.artifacthub.package.readme-url: https://raw.githubusercontent.com/nocderechte/bridget/main/README.md
      io.artifacthub.package.license: GPL-3.0
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.name: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "{{ .GitURL }}"

    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
