volumes:
  influxdb_data:
  mosquitto_data:

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - mosquitto_data:/mosquitto/data:rw
      - ./mosquitto/config:/mosquitto/config:ro
    restart: unless-stopped
  influxdb:
    image: influxdb:3-core
    command: serve --node-id=db1 --object-store=file --data-dir=/var/lib/influxdb3
    ports:
      - 8181:8181
    volumes:
      - influxdb_data:/var/lib/influxdb3
    restart: unless-stopped

  bridget:
    build: ./../..
    volumes:
      - ./bridget/config:/etc/bridget
    env_file:
      - .env_example
    depends_on:
      - mqtt
      - influxdb
    restart: unless-stopped
