volumes:
  influxdb_data:

services:
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
  influxdb:
    image: influxdb:3-core
    command: serve --node-id=${INFLUXDB_NODE_ID} --object-store=file --data-dir=/var/lib/influxdb3
    ports:
      - 8181:8181
    volumes:
      - influxdb_data:/var/lib/influxdb3
      - ./influxdb/config:/etc/influxdb3
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
    restart: unless-stopped
