name: build and test

on:
  push:
  pull_request:
  workflow_call:

jobs:
  test:
    name: Build and test application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
          cache: true

      - run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8

      - name: Run tests
        run: go test -race -vet=off ./...

      - name: Download dependencies
        run: go mod download

      - name: Build app
        run: go build -v ./...
